/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arbolE;

import java.awt.Color;
import java.util.HashMap;

/**
 *
 * @author Perso
 */
public class color extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(color.class.getName());

    /**
     * Creates new form color
     */
    public color() {
        initComponents();
    }
    
    private PanelArbol panel;

    public color(PanelArbol panel) {
    initComponents();
    this.panel = panel;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtColorLinea = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtColorContorno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGrosorLinea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGrosorContorno = new javax.swing.JTextField();
        txtG = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Color linea:");

        txtColorLinea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtColorLineaKeyReleased(evt);
            }
        });

        jLabel2.setText("Color contorno:");

        txtColorContorno.addActionListener(this::txtColorContornoActionPerformed);
        txtColorContorno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtColorContornoKeyReleased(evt);
            }
        });

        jLabel3.setText("Color nodo (RGB):");

        txtR.addActionListener(this::txtRActionPerformed);
        txtR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRKeyReleased(evt);
            }
        });

        jLabel4.setText("Grosor linea:");

        txtGrosorLinea.addActionListener(this::txtGrosorLineaActionPerformed);
        txtGrosorLinea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrosorLineaKeyReleased(evt);
            }
        });

        jLabel5.setText("Grosor contorno:");

        txtG.addActionListener(this::txtGActionPerformed);
        txtG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGKeyReleased(evt);
            }
        });

        txtB.addActionListener(this::txtBActionPerformed);
        txtB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBKeyReleased(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(25, 25, 25)
                            .addComponent(txtGrosorContorno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(154, 154, 154)))
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtColorContorno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtR, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtG, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtColorLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGrosorLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtColorLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtColorContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGrosorLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGrosorContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGrosorLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrosorLineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrosorLineaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HashMap<String,String> valor= ArbolAgenteIA.tablaSimbolos;
        System.out.println(valor);
        
        
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtColorLineaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorLineaKeyReleased
        // TODO add your handling code here:
         panel.setColorLinea(txtColorLinea.getText());
    }//GEN-LAST:event_txtColorLineaKeyReleased

    private void txtColorContornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorContornoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtColorContornoActionPerformed

    private void txtColorContornoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorContornoKeyReleased
        // TODO add your handling code here:
        panel.setColorContorno(txtColorContorno.getText());
    }//GEN-LAST:event_txtColorContornoKeyReleased

    private void txtRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtRActionPerformed

    private void txtGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtGActionPerformed

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtBActionPerformed

    private void txtRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRKeyReleased
        // TODO add your handling code here:
            if (txtR.getText().isBlank()
                    || txtG.getText().isBlank()
                    || txtB.getText().isBlank()) {
                return;
            }           
                    int r = Integer.parseInt(txtR.getText());
            int g = Integer.parseInt(txtG.getText());
            int b = Integer.parseInt(txtB.getText());

            panel.setColorNodo(r, g, b);
    }//GEN-LAST:event_txtRKeyReleased

    private void txtGKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGKeyReleased
        // TODO add your handling code here:
            if (txtR.getText().isBlank()
                    || txtG.getText().isBlank()
                    || txtB.getText().isBlank()) {
                return;
            }   
                    int r = Integer.parseInt(txtR.getText());
            int g = Integer.parseInt(txtG.getText());
            int b = Integer.parseInt(txtB.getText());

            panel.setColorNodo(r, g, b);
    }//GEN-LAST:event_txtGKeyReleased

    private void txtBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBKeyPressed

    private void txtBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBKeyReleased
        // TODO add your handling code here:
            if (txtR.getText().isBlank()
                    || txtG.getText().isBlank()
                    || txtB.getText().isBlank()) {
                return;
            }   
                    int r = Integer.parseInt(txtR.getText());
            int g = Integer.parseInt(txtG.getText());
            int b = Integer.parseInt(txtB.getText());

            panel.setColorNodo(r, g, b);
    }//GEN-LAST:event_txtBKeyReleased

    private void txtGrosorLineaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrosorLineaKeyReleased
        // TODO add your handling code here:
        float grosor = Float.parseFloat(txtGrosorLinea.getText());
        panel.setGrosorLinea(grosor);
    }//GEN-LAST:event_txtGrosorLineaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new color().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtColorContorno;
    private javax.swing.JTextField txtColorLinea;
    private javax.swing.JTextField txtG;
    private javax.swing.JTextField txtGrosorContorno;
    private javax.swing.JTextField txtGrosorLinea;
    private javax.swing.JTextField txtR;
    // End of variables declaration//GEN-END:variables
}
